apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  rag-n8n-shared-pvc
  namespace: ollama
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard