apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name:  n8n-data
  namespace: ollama
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: ollama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n8n
          image: n8nio/n8n:latest
          ports:
            - containerPort: 5678
          env:
            - name: N8N_BASIC_AUTH_ACTIVE
              value: "false"
            - name: N8N_HOST
              value: "0.0.0.0"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_DEFAULT_LOCALE
              value: "en"
            - name: N8N_LOG_LEVEL
              value: "info"
            - name: N8N_PERSONALIZATION_ENABLED
              value: "false"
            - name: GENERIC_TIMEZONE
              value: "UTC"
            - name: N8N_PATH
              value: "/"
          volumeMounts:
            - mountPath: /home/node/.n8n
              name: n8n-data
            - mountPath: /data
              name: shared-data
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data
        - name: shared-data
          persistentVolumeClaim:
            claimName: rag-n8n-shared-pvc


---
apiVersion: v1
kind: Service
metadata:
  name: n8n 
  namespace: ollama
spec:
  selector:
    app: n8n
  ports:
  - name: web
    port: 80
    targetPort: 5678
    protocol: TCP
  - name: webhook
    port: 5678
    targetPort: 5678
    protocol: TCP

